# Version: 0.0.1
# @edt M06 2018-2019
# samba
# -------------------------------------
FROM fedora:27
LABEL author="@edt ASIX M06-ASO"
LABEL description="SAMBA server 2018-2019"
RUN dnf -y install procps samba passwd samba-client vim nss-pam-ldapd openldap-clients smbldap-tools
RUN mkdir /opt/docker
COPY * /opt/docker/
RUN chmod +x /opt/docker/install.sh /opt/docker/startup.sh /opt/docker/smbhomes.sh /opt/docker/smbusers.sh
WORKDIR /opt/docker
CMD ["/opt/docker/startup.sh"]

